services:
  prometheus:
    restart: always
    image: prom/prometheus
    ports:
      - "9090:9090"
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml


  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"